package com.bhirava.ovilearning.ui.util;

public enum AnimationMode {

	ONCE, REPEAT, REPEAT_KILL_ON_HOVER, REPEAT_PAUSE_ON_HOVER, REPEAT_FOR, ON_HOVER, ON_HOVER_KILL_ON_LEAVE, ON_HOVER_PAUSE_ON_LEAVE, ON_MOUSE_OUT, ON_MOUSE_OUT_KILL_ON_LEAVE, ON_MOUSE_OUT_PAUSE_ON_LEAVE, ON_CLICK

}
